# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza-django
  template:
    metadata:
      labels:
        app: pizza-django
    spec:
      containers:
      - name: pizza-django
        image: <dockerhub-username>/pizza-django:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-django-service
spec:
  selector:
    app: pizza-django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer


