# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza_django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza_django
  template:
    metadata:
      labels:
        app: pizza_django
    spec:
      containers:
      - name: pizza_django
        image: <dockerhub-username>/pizza_django:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pizza_django-service
spec:
  selector:
    app: pizza_django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer


