version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pizza_ordering
      POSTGRES_USER: pizza_user
      POSTGRES_PASSWORD: pizza_password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - main

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - main
    environment:
      DB_NAME: pizza_ordering
      DB_USER: pizza_user
      DB_PASSWORD: pizza_password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

networks:
  main:

volumes:
  postgres_data:
