version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test

  build:
    executor: docker-executor
    steps:
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_ORG/$DOCKERHUB_REPO:$CIRCLE_BRANCH .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push $DOCKERHUB_ORG/$DOCKERHUB_REPO:$CIRCLE_BRANCH

  deploy:
    executor: docker-executor
    steps:
      - run:
          name: Install Kubernetes CLI
          command: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl config use-context $KUBE_CONTEXT
            kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$DOCKERHUB_ORG/$DOCKERHUB_REPO:$CIRCLE_BRANCH

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master



