# Generated by Django 3.2.19 on 2023-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizza_django", "0002_auto_20230516_0500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="count",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="flavor",
            field=models.CharField(
                choices=[
                    ("MG", "Margarita"),
                    ("MR", "Marinara"),
                    ("SL", "Salami"),
                    ("<class 'pizza_django.models.PizzaFlavor.Meta'>", "Meta"),
                ],
                default="MG",
                max_length=46,
            ),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="size",
            field=models.CharField(
                choices=[
                    ("SM", "Small"),
                    ("MD", "Medium"),
                    ("LG", "Large"),
                    ("<class 'pizza_django.models.PizzaSize.Meta'>", "Meta"),
                ],
                default="SM",
                max_length=46,
            ),
        ),
    ]
