# Generated by Django 3.2.19 on 2023-05-16 11:02

from django.db import migrations


def create_sample_customers(apps, schema_editor):
    Customer = apps.get_model("pizza_django", "Customer")
    Customer.objects.create(name="John Doe", address="123 Elm St")
    Customer.objects.create(name="Jane Smith", address="456 Oak St")


class Migration(migrations.Migration):
    dependencies = [
        ("pizza_django", "0003_auto_20230516_1030"),
    ]

    operations = []
