# Generated by Django 3.2.19 on 2023-05-16 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizza_django", "0004_auto_20230516_1102"),
    ]

    operations = []
